"""updated cart_item3

Revision ID: 0583b5baa546
Revises: bab370e140b1
Create Date: 2023-11-22 14:04:49.117473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0583b5baa546'
down_revision: Union[str, None] = 'bab370e140b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('customer_id', sa.String(length=60), nullable=True))
    op.add_column('cart_items', sa.Column('vendor_id', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'vendor_id')
    op.drop_column('cart_items', 'customer_id')
    # ### end Alembic commands ###
