"""updated order table

Revision ID: 35320373f86d
Revises: 0693be8e8239
Create Date: 2023-11-19 23:22:55.560194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35320373f86d'
down_revision: Union[str, None] = '0693be8e8239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('items', sa.JSON(), nullable=False))
    op.add_column('orders', sa.Column('customer', sa.JSON(), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Integer(), nullable=False))
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'item_price')
    op.drop_column('orders', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('item_price', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer_id', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'customer')
    op.drop_column('orders', 'items')
    # ### end Alembic commands ###
