"""added count to tables

Revision ID: 50be441629f3
Revises: 35320373f86d
Create Date: 2023-11-20 01:22:22.862409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50be441629f3'
down_revision: Union[str, None] = '35320373f86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'count')
    op.drop_column('cart_items', 'count')
    # ### end Alembic commands ###
