"""updated cart_item table

Revision ID: 668b4766f3b2
Revises: 40f81605f197
Create Date: 2023-11-21 14:26:37.839195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668b4766f3b2'
down_revision: Union[str, None] = '40f81605f197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'customer_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('cart_items', 'vendor_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'vendor_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('cart_items', 'customer_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
