"""updated vendor column

Revision ID: eb8775c3d71d
Revises: 8101ba6a8480
Create Date: 2023-11-21 12:04:07.807160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8775c3d71d'
down_revision: Union[str, None] = '8101ba6a8480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'customer_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('cart_items', 'vendor_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.add_column('vendors', sa.Column('name', sa.String(length=60), nullable=True))
    op.drop_column('vendors', 'first_name')
    op.drop_column('vendors', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('last_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('first_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('vendors', 'name')
    op.alter_column('cart_items', 'vendor_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('cart_items', 'customer_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
