"""updated vendor table2

Revision ID: ebbb99f58fa6
Revises: 2c5b84cdce82
Create Date: 2023-11-21 15:36:25.373107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbb99f58fa6'
down_revision: Union[str, None] = '2c5b84cdce82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
